-- Part of the DungeonJournal RAIDS database (see AGENTS.md "Data model").
-- Loaded via DungeonJournal.toc before DungeonJournal.lua; appends this
-- raid's table to the shared DungeonJournal_Raids list in load order.

DungeonJournal_Raids = DungeonJournal_Raids or {}

------------------------------------------------------------
-- SM order list - START HERE to reorder bosses.
--
-- SM_BOSS_ORDER is the only thing you should need to touch to change
-- what order bosses appear in the Bosses tab. It's just a flat list of
-- keys - actual boss data (icon/flags/stats/abilities) lives further
-- down in SM_BOSSES, defined once per key and looked up from here.
------------------------------------------------------------

-- Boss encounter order (Bosses tab tree, top to bottom).
local SM_BOSS_ORDER = {
    "loksey",
    "brigitte",
    "vishas",
    "herod",
    "brother_michael",
    "doan",
    "renault_mograine",
    "fairbanks",
}

-- CHANGED: trash roster sourced from a real combat log ("Scarlet Monestary
-- Trash (most of it).csv" - Source/Action/Spell ID columns), cross-matched
-- against Spell.xlsx by exact Spell ID for icons/descriptions. Pull
-- order/grouping is NOT known from that log (it's a flat event list, no
-- pull boundaries), so this is just every distinct mob that logged an
-- ability, in no particular order - see TODO_Raid_Data.md.
local SM_TRASH_ORDER = {
    "scarlet_soldier",
    "scarlet_guardsman",
    "scarlet_defender",
    "scarlet_centurion",
    "scarlet_champion",
    "scarlet_myrmidon",
    "scarlet_monk",
    "scarlet_torturer",
    -- CHANGED: Scarlet Sharpshooter removed from trash - it's already an
    -- add of Brigitte Abbendis (see her boss entry), not a standalone pull.
    -- CHANGED: Scarlet Recruit removed - not a real trash pull.
    -- CHANGED: Scarlet Trainee removed from trash - confirmed to be
    -- Herod's death-summon add instead (see his boss entry).
    -- CHANGED: trash packs have no "adds" UI (unlike bosses - see
    -- TODO_Raid_Data.md), so Beastmaster and its Hound are listed as two
    -- separate, ungrouped trash pulls rather than a merged pack.
    "scarlet_tracking_hound",
    "scarlet_beastmaster",
    "scarlet_sorcerer",
    "scarlet_wizard",
    "scarlet_evoker",
    "scarlet_conjuror",
    "scarlet_abbot",
    "scarlet_adept",
    "scarlet_chaplain",
    "scarlet_protector",
    "scarlet_gallant",
    "scarlet_diviner",
}

------------------------------------------------------------
-- Trash mob registry - one entry per distinct trash mob (icon/flags/
-- stats/abilities), referenced by key from SM_TRASH_ORDER above.
------------------------------------------------------------
local SM_TRASH_MOBS = {
    scarlet_soldier = {
        name = "Scarlet Soldier",
        icon = "Interface\\Icons\\Ability_Warrior_Sunder",
        flags = {"melee"},
        -- CHANGED: from a real combat log (see Scarlet Monestary Trash CSV) -
        -- stats not present in that log, never tested.
        stats = {armor = "X", fire = "X", nature = "X", frost = "X", shadow = "X", arcane = "X"},
        abilities = {{
            name = "Sunder Armor",
            icon = "Interface\\Icons\\Ability_Warrior_Sunder",
            warning = true,
            lines = {"Sunders the target's armor, reducing it by 820 per stack (up to 5 stacks) and causing a high amount of threat. Lasts 30 seconds."}
        }, {
            separator = true,
            passive = true,
            name = "Passives"
        }, {
            name = "Improved Blocking",
            icon = "Interface\\Icons\\Ability_Defend",
            lines = {"Increases the caster's chance to block by 55%."}
        }}
    },

    scarlet_guardsman = {
        name = "Scarlet Guardsman",
        icon = "Interface\\Icons\\Ability_Warrior_Disarm",
        flags = {"melee"},
        -- CHANGED: from a real combat log (see Scarlet Monestary Trash CSV) -
        -- stats not present in that log, never tested.
        stats = {armor = "X", fire = "X", nature = "X", frost = "X", shadow = "X", arcane = "X"},
        abilities = {{
            name = "Disarm",
            icon = "Interface\\Icons\\Ability_Warrior_Disarm",
            warning = true,
            lines = {"Disarms the enemy's weapon for 6 seconds."}
        }, {
            name = "Impale",
            icon = "Interface\\Icons\\Ability_Gouge",
            -- CHANGED: matched spell ID 36051 (>=35800, this content pack's custom range).
            lines = {"Wounds the target, causing it to bleed for 450 damage every 3 sec."}
        }, {
            separator = true,
            passive = true,
            name = "Passives"
        }, {
            name = "Defensive Stance",
            icon = "Interface\\Icons\\Ability_Warrior_DefensiveStance",
            lines = {"A defensive combat stance that decreases damage taken by 10% and damage caused by 10%. Increases threat generated by 30%."}
        }, {
            -- CHANGED: matched spell ID 36047 (custom range) - aura text is just "Disarmed.",
            -- duration/proc chance not confirmed from durationIndex alone.
            name = "Riposte",
            icon = "Interface\\Icons\\Ability_Warrior_Challange",
            lines = {"A counterattack that disarms the enemy's weapon for 5 seconds."}
        }}
    },

    scarlet_defender = {
        name = "Scarlet Defender",
        icon = "Interface\\Icons\\Ability_Warrior_Sunder",
        flags = {"melee"},
        -- CHANGED: from a real combat log (see Scarlet Monestary Trash CSV) -
        -- stats not present in that log, never tested.
        stats = {armor = "X", fire = "X", nature = "X", frost = "X", shadow = "X", arcane = "X"},
        abilities = {{
            name = "Rebuke",
            icon = "Interface\\Icons\\INV_Shield_05",
            lines = {"Deals damage with a shield to targets in front of the caster, interrupting spellcasting."}
        }, {
            name = "Sunder Armor",
            icon = "Interface\\Icons\\Ability_Warrior_Sunder",
            warning = true,
            lines = {"Sunders the target's armor, reducing it by 820 per stack (up to 5 stacks) and causing a high amount of threat. Lasts 30 seconds."}
        }, {
            separator = true,
            passive = true,
            name = "Passives"
        }, {
            name = "Defensive Stance",
            icon = "Interface\\Icons\\Ability_Warrior_DefensiveStance",
            lines = {"A defensive combat stance that decreases damage taken by 10% and damage caused by 10%. Increases threat generated by 30%."}
        }, {
            name = "Improved Blocking",
            icon = "Interface\\Icons\\Ability_Defend",
            lines = {"Increases the caster's chance to block by 55%."}
        }}
    },

    scarlet_centurion = {
        name = "Scarlet Centurion",
        icon = "Interface\\Icons\\Spell_Nature_ThunderClap",
        flags = {"melee"},
        -- CHANGED: from a real combat log (see Scarlet Monestary Trash CSV) -
        -- stats not present in that log, never tested.
        stats = {armor = "X", fire = "X", nature = "X", frost = "X", shadow = "X", arcane = "X"},
        abilities = {{
            -- CHANGED: radius confirmed from Spell.xlsx (spell 36043) + SpellRadius.csv lookup - not in-game tested.
            name = "Battle Shout",
            icon = "Interface\\Icons\\Ability_Warrior_BattleShout",
            lines = {"Shouts, increasing damage done of nearby allies within 30 yards by 30%. Lasts 20 seconds."}
        }, {
            name = "Charge",
            icon = "Interface\\Icons\\Ability_Warrior_Charge",
            warning = true,
            lines = {"Charges an enemy, inflicting normal damage plus 500 and stunning it for 3 seconds."}
        }, {
            name = "Thunder Clap",
            icon = "Interface\\Icons\\Spell_Nature_ThunderClap",
            warning = true,
            lines = {"Blasts nearby enemies with thunder, inflicting 2250 to 2500 damage and reducing their movement and attack speed by 20% for 18 seconds."}
        }, {
            separator = true,
            passive = true,
            name = "Passives"
        }, {
            name = "Battle Stance",
            icon = "Interface\\Icons\\Ability_Warrior_OffensiveStance",
            lines = {"A balanced combat stance."}
        }, {
            -- CHANGED: duration confirmed from Spell.xlsx (spell 22857) + SpellDuration.csv lookup - not in-game tested.
            name = "Retaliation",
            icon = "Interface\\Icons\\Ability_Warrior_Challange",
            lines = {"Instantly counterattacks any enemy that strikes it in melee for 15 seconds. Attacks from behind cannot be counterattacked."}
        }}
    },

    scarlet_champion = {
        name = "Scarlet Champion",
        icon = "Interface\\Icons\\Ability_Racial_Avatar",
        flags = {"melee"},
        -- CHANGED: from a real combat log (see Scarlet Monestary Trash CSV) -
        -- stats not present in that log, never tested.
        stats = {armor = "X", fire = "X", nature = "X", frost = "X", shadow = "X", arcane = "X"},
        abilities = {{
            -- CHANGED: found via Spell.xlsx (id 36269, linked to 36270 "Duelling!" aura) -
            -- the live DBC site's 20-result cap on "Duel" hid this custom-range match.
            name = "Duel",
            icon = "Interface\\Icons\\Ability_Warrior_Challange",
            lines = {"Forces the target to attack the caster for 5 seconds."},
            abilities = {{
                -- CHANGED: matched spell ID 36132 (custom range). Confirmed correct at
                -- -1% (not implausible) - user confirmed this is granted to the player
                -- when they die during/after losing the duel. Duration index 367 = 2 hours.
                name = "Duel Loooser",
                icon = "Interface\\Icons\\Spell_Shadow_MindSteal",
                lines = {"Applied when the duel ends in the caster's death. All stats reduced by 1% for 2 hours."}
            }, {
                -- CHANGED: found via Spell.xlsx (id 36131, "Duel Winner (Player)") - granted
                -- to the player when Scarlet Champion dies while duelling them. Duration
                -- index 367 = 2 hours, matches Duel Loooser's duration. Confirmed via
                -- goralia.sk DBC lookup: effectAura_2 is AuraModScale (the size increase)
                -- and effect_3 is EffectHealMaxHealth (heals to full on grant).
                name = "Duel Winner",
                icon = "Interface\\Icons\\Ability_Racial_Avatar",
                lines = {"Granted when the Champion dies while duelling. Heals to full, increases damage done by 1%, and increases size by 5%. Lasts 2 hours."}
            }}
        }, {
            -- CHANGED: Spell.xlsx "Vengeance" entries (36127, 36129) are empty;
            -- values below are from user report, not tested.
            name = "Vengeance",
            icon = "Interface\\Icons\\Ability_Racial_Avatar",
            warning = true,
            lines = {"Every 15 seconds the Champion grows in size, then after 3 seconds all damage dealt to him is reflected to everyone within 10 yards."}
        }}
    },

    scarlet_myrmidon = {
        name = "Scarlet Myrmidon",
        icon = "Interface\\Icons\\Ability_Rogue_Sprint",
        flags = {"melee"},
        -- CHANGED: from a real combat log (see Scarlet Monestary Trash CSV) -
        -- stats not present in that log, never tested.
        stats = {armor = "X", fire = "X", nature = "X", frost = "X", shadow = "X", arcane = "X"},
        abilities = {{
            name = "Intercept",
            icon = "Interface\\Icons\\Ability_Rogue_Sprint",
            warning = true,
            -- CHANGED: matched spell ID 36078 (custom range) via Spell.xlsx.
            lines = {"Charges an enemy, inflicting normal damage plus 800 and stunning it for 4 seconds."}
        }, {
            -- CHANGED: Spell.xlsx id 36080; damage and 1%-per-stack healing
            -- reduction (up to 50 stacks) confirmed by user report.
            name = "Rend",
            icon = "Interface\\Icons\\Ability_Gouge",
            lines = {"Bleeding for 75 damage every 3 sec. Each application also reduces healing effects on the target by 1%, stacking up to 50 times."}
        }, {
            separator = true,
            passive = true,
            name = "Passives"
        }, {
            name = "Berserker Stance",
            icon = "Interface\\Icons\\Ability_Racial_Avatar",
            lines = {"An aggressive stance. Increases critical strike chance by 3%. Increases the chance to be critically hit by 10%. Reduces threat generated by 20%."}
        }}
    },

    scarlet_monk = {
        name = "Scarlet Monk",
        icon = "Interface\\Icons\\Ability_Kick",
        flags = {"melee"},
        -- CHANGED: from a real combat log (see Scarlet Monestary Trash CSV) -
        -- stats not present in that log, never tested.
        stats = {armor = "X", fire = "X", nature = "X", frost = "X", shadow = "X", arcane = "X"},
        abilities = {{
            name = "Fist of the Third Moon",
            icon = "Interface\\Icons\\INV_Gauntlets_04",
            warning = true,
            lines = {"An instant combo attack - the third strike unleashes a Devastating Blow."},
            abilities = {{
                name = "Devastating Blow",
                icon = "Interface\\Icons\\Spell_Fire_Volcano",
                lines = {"Deals 5000 to 6000 damage."}
            }}
        }, {
            name = "Inner Fire",
            icon = "Interface\\Icons\\Spell_Holy_InnerFire",
            lines = {"Increases a friendly unit's damage by 20% and reduces its damage taken by 20% for 60 seconds."}
        }, {
            name = "Kick",
            icon = "Interface\\Icons\\Ability_Kick",
            warning = true,
            lines = {"Kicks the target, dealing 2500 to 3000 damage and knocking it down for 10 seconds."}
        }}
    },

    scarlet_torturer = {
        name = "Scarlet Torturer",
        icon = "Interface\\Icons\\Ability_Gouge",
        flags = {"melee"},
        -- CHANGED: from a real combat log (see Scarlet Monestary Trash CSV) -
        -- stats not present in that log, never tested.
        stats = {armor = "X", fire = "X", nature = "X", frost = "X", shadow = "X", arcane = "X"},
        abilities = {{
            name = "Gouge",
            icon = "Interface\\Icons\\Ability_Gouge",
            warning = true,
            lines = {"Inflicts 1911 to 2289 damage to an enemy and stuns it for up to 6 seconds. Target must be facing the caster."}
        }, {
            name = "Immolate",
            icon = "Interface\\Icons\\Spell_Fire_Immolation",
            warning = true,
            lines = {"Burns an enemy for 300, then an additional 795 to 945 Fire damage every 3 sec, for 21 seconds."}
        }, {
            name = "Sear",
            icon = "Interface\\Icons\\Spell_Fire_FlameShock",
            warning = true,
            lines = {"Flame Lash for 520 to 640 Fire damage."}
        }}
    },

    scarlet_tracking_hound = {
        name = "Scarlet Tracking Hound",
        icon = "Interface\\Icons\\Ability_Hunter_KillCommand",
        flags = {"melee"},
        -- CHANGED: from a real combat log (see Scarlet Monestary Trash CSV) -
        -- stats not present in that log, never tested.
        stats = {armor = "X", fire = "X", nature = "X", frost = "X", shadow = "X", arcane = "X"},
        abilities = {{
            separator = true,
            passive = true,
            name = "Passives"
        }, {
            name = "Infected Wound",
            icon = "Interface\\Icons\\spell_nature_nullifydisease",
            roles = {"dispel"},
            lines = {"Hounds apply a stacking debuff which increases physical damage taken by 3 per stack up to 99 stacks."}
        }}
    },

    scarlet_beastmaster = {
        name = "Scarlet Beastmaster",
        icon = "Interface\\Icons\\Ability_Hunter_Quickshot",
        flags = {"ranged"},
        -- CHANGED: from a real combat log (see Scarlet Monestary Trash CSV) -
        -- stats not present in that log, never tested.
        stats = {armor = "X", fire = "X", nature = "X", frost = "X", shadow = "X", arcane = "X"},
        abilities = {{
            name = "Kill Command",
            icon = "Interface\\Icons\\Ability_Hunter_KillCommand",
            lines = {"Command your pet to kill the weakest enemy, making it immune to Taunt effects and increasing its movement speed by 50% for 10 seconds."}
        }, {
            name = "Scatter Shot",
            icon = "Interface\\Icons\\Ability_GolemStormBolt",
            warning = true,
            lines = {"A short-range shot that deals 100% weapon damage and disorients the target for 8 seconds."}
        }, {
            name = "Serpent Sting",
            icon = "Interface\\Icons\\Ability_Hunter_Quickshot",
            warning = true,
            lines = {"Stings the target, causing 1800 Nature damage over 15 seconds."}
        }, {
            name = "Summon Scarlet Tracking Hound",
            icon = "Interface\\Icons\\Ability_Mount_WhiteDireWolf",
            lines = {"Summons a Scarlet Tracking Hound to aid it in battle."}
        }}
    },

    scarlet_sorcerer = {
        name = "Scarlet Sorcerer",
        icon = "Interface\\Icons\\Spell_Nature_StarFall",
        flags = {"caster"},
        -- CHANGED: from a real combat log (see Scarlet Monestary Trash CSV) -
        -- stats not present in that log, never tested.
        stats = {armor = "X", fire = "X", nature = "X", frost = "X", shadow = "X", arcane = "X"},
        abilities = {{
            name = "Arcanebolt",
            icon = "Interface\\Icons\\Spell_Nature_StarFall",
            warning = true,
            roles = {"kick"},
            lines = {"Blasts an enemy with Arcane magic, inflicting 1040 to 1390 Arcane damage."}
        }, {
            name = "Polymorph",
            icon = "Interface\\Icons\\Spell_Nature_Polymorph",
            warning = true,
            lines = {"Transforms an enemy into a sheep for up to 15 seconds."}
        }, {
            name = "Slow",
            icon = "Interface\\Icons\\Spell_Nature_Slow",
            warning = true,
            lines = {"Slows the enemy's movement and attack speed by 50% for 20 seconds."}
        }, {
            separator = true,
            passive = true,
            name = "Passives"
        }, {
            name = "Mana Shield",
            icon = "Interface\\Icons\\Spell_Shadow_DetectLesserInvisibility",
            lines = {"Cast once at the start of combat. Absorbs all incoming damage by draining its own mana instead, and holds until the Sorcerer runs out of mana - effectively the whole fight unless its mana is burned down."}
        }}
    },

    scarlet_wizard = {
        name = "Scarlet Wizard",
        icon = "Interface\\Icons\\Spell_Frost_FrostBolt02",
        flags = {"caster"},
        -- CHANGED: from a real combat log (see Scarlet Monestary Trash CSV) -
        -- stats not present in that log, never tested.
        stats = {armor = "X", fire = "X", nature = "X", frost = "X", shadow = "X", arcane = "X"},
        abilities = {{
            -- CHANGED: matched spell ID 36145 (custom range).
            name = "Chilled",
            icon = "Interface\\Icons\\Spell_Frost_FrostArmor02",
            lines = {"Movement slowed by 40% and time between attacks increased by 80%."}
        }, {
            name = "Cone of Cold",
            icon = "Interface\\Icons\\Spell_Frost_Glacier",
            warning = true,
            lines = {"Targets in a cone in front of the caster take 3450 to 3920 Frost damage, are knocked back, and are slowed by 70% for 8 seconds."}
        }, {
            -- CHANGED: matched spell ID 36149 (custom range).
            name = "Cryo Zone",
            icon = "Interface\\Icons\\Spell_Frost_FrostNova",
            lines = {"Movement speed slowed by 70%. Increases Frost damage taken by 100%."}
        }, {
            -- CHANGED: found via Spell.xlsx (id 36092, linked to 36093 for the damage
            -- value) - the live DBC site's 20-result cap on "Fire Shield" hid this.
            name = "Fire Shield",
            icon = "Interface\\Icons\\Spell_Fire_Immolation",
            lines = {"Surrounds nearby allies with a shield of flame that inflicts 495 Fire damage to nearby enemies every 3 sec. Lasts 60 seconds."}
        }, {
            name = "Frostbolt",
            icon = "Interface\\Icons\\Spell_Frost_FrostBolt02",
            warning = true,
            roles = {"kick"},
            lines = {"Launches a bolt of frost, causing 2315 to 2615 Frost damage and slowing movement speed by 40% for 7 seconds."}
        }, {
            name = "Frozen",
            icon = "Interface\\Icons\\Spell_Frost_FrostNova",
            warning = true,
            lines = {"Blasts nearby enemies for 1800 to 2100 Frost damage and freezes them in place for up to 4 seconds. Damage taken may break the freeze."}
        }, {
            name = "Ice Block",
            icon = "Interface\\Icons\\Spell_Frost_Frost",
            lines = {"Becomes immune to all physical attacks and spells for 10 seconds, but cannot attack, move, or cast during that time."}
        }, {
            name = "Summon Water Elemental",
            icon = "Interface\\Icons\\Spell_Frost_SummonWaterElemental",
            lines = {"Summons a Water Elemental to aid it for 90 seconds."}
        }}
    },

    scarlet_evoker = {
        name = "Scarlet Evoker",
        icon = "Interface\\Icons\\Spell_Fire_SelfDestruct",
        flags = {"caster"},
        -- CHANGED: from a real combat log (see Scarlet Monestary Trash CSV) -
        -- stats not present in that log, never tested.
        stats = {armor = "X", fire = "X", nature = "X", frost = "X", shadow = "X", arcane = "X"},
        abilities = {{
            -- CHANGED: matched spell ID 36088 (custom range).
            name = "Fiery Purge",
            icon = "Interface\\Icons\\Spell_Fire_Fireball",
            lines = {"Purges an enemy target, removing 1 magic effect."}
        }, {
            -- CHANGED: found via Spell.xlsx (id 36092, linked to 36093 for the damage
            -- value) - the live DBC site's 20-result cap on "Fire Shield" hid this.
            name = "Fire Shield",
            icon = "Interface\\Icons\\Spell_Fire_Immolation",
            roles = {"dispel"},
            lines = {"Surrounds nearby allies with a shield of flame that inflicts 495 Fire damage to nearby enemies every 3 sec. Lasts 60 seconds."}
        }, {
            name = "Fireball",
            icon = "Interface\\Icons\\Spell_Fire_FlameBolt",
            warning = true,
            roles = {"kick"},
            lines = {"Hurls a fiery ball that causes 1796 to 2170 Fire damage and an additional 460 Fire damage over 8 seconds."}
        }, {
            name = "Flamestrike",
            icon = "Interface\\Icons\\Spell_Fire_SelfDestruct",
            warning = true,
            lines = {"Calls down a pillar of fire, burning all enemies within the area for 880 to 1264 Fire damage and an additional 490 Fire damage over 8 seconds."}
        }, {
            -- CHANGED: spell ID 36086; effectBasePoints 99 -> 100 via the +1 formula,
            -- confirmed by user as removing up to 100 effects.
            name = "Purifying Flames",
            icon = "Interface\\Icons\\Spell_Fire_Fireball",
            lines = {"Cleanses a friendly target, removing up to 100 curse, disease, and magic effects.",
                     "Heals for 1000 to 1100 every 2 sec. Lasts 8 seconds."}
        }}
    },

    scarlet_conjuror = {
        name = "Scarlet Conjuror",
        icon = "Interface\\Icons\\Spell_Fire_FlameBolt",
        flags = {"caster"},
        -- CHANGED: from a real combat log (see Scarlet Monestary Trash CSV) -
        -- stats not present in that log, never tested.
        stats = {armor = "X", fire = "X", nature = "X", frost = "X", shadow = "X", arcane = "X"},
        abilities = {{
            -- CHANGED: spell ID 36110; restore-to-full and trigger conditions
            -- from user report, not tested.
            name = "Consume Elemental",
            icon = "Interface\\Icons\\Spell_Shadow_SacrificialShield",
            warning = true,
            lines = {"Consumes one of its elementals, restoring itself to full health and mana. Only used when at low health, and at most once every 30 seconds.",
                     "Can be cast while crowd controlled."}
        }, {
            name = "Fireball",
            icon = "Interface\\Icons\\Spell_Fire_FlameBolt",
            warning = true,
            roles = {"kick"},
            lines = {"Hurls a fiery ball that causes 1796 to 2170 Fire damage and an additional 460 Fire damage over 8 seconds."}
        }}
    },

    scarlet_abbot = {
        name = "Scarlet Abbot",
        icon = "Interface\\Icons\\Spell_Holy_GreaterHeal",
        flags = {"caster"},
        -- CHANGED: from a real combat log (see Scarlet Monestary Trash CSV) -
        -- stats not present in that log, never tested.
        stats = {armor = "X", fire = "X", nature = "X", frost = "X", shadow = "X", arcane = "X"},
        abilities = {{
            name = "Flash Heal",
            icon = "Interface\\Icons\\Spell_Holy_FlashHeal",
            roles = {"kick"},
            lines = {"Heals a friendly target for 6450 to 8050."}
        }, {
            name = "Greater Heal",
            icon = "Interface\\Icons\\Spell_Holy_GreaterHeal",
            roles = {"kick"},
            lines = {"A slow casting spell that heals a single target for 18900 to 22100."}
        }, {
            name = "Renew",
            icon = "Interface\\Icons\\Spell_Holy_Renew",
            roles = {"dispel"},
            lines = {"Heals the target for a total of 2100 over 15 seconds."}
        }}
    },

    scarlet_adept = {
        name = "Scarlet Adept",
        icon = "Interface\\Icons\\Spell_Holy_HolySmite",
        flags = {"caster"},
        -- CHANGED: from a real combat log (see Scarlet Monestary Trash CSV) -
        -- stats not present in that log, never tested.
        stats = {armor = "X", fire = "X", nature = "X", frost = "X", shadow = "X", arcane = "X"},
        abilities = {{
            name = "Heal",
            icon = "Interface\\Icons\\Spell_Holy_Heal",
            roles = {"kick"},
            lines = {"Heals its target for 8300 to 9850."}
        }, {
            name = "Smite",
            icon = "Interface\\Icons\\Spell_Holy_HolySmite",
            warning = true,
            lines = {"Smites an enemy for 1800 to 2100 Holy damage."}
        }}
    },

    scarlet_chaplain = {
        name = "Scarlet Chaplain",
        icon = "Interface\\Icons\\Spell_Holy_PrayerOfFortitude",
        flags = {"caster"},
        -- CHANGED: from a real combat log (see Scarlet Monestary Trash CSV) -
        -- stats not present in that log, never tested.
        stats = {armor = "X", fire = "X", nature = "X", frost = "X", shadow = "X", arcane = "X"},
        abilities = {{
            name = "Power Word: Requital",
            icon = "Interface\\Icons\\Spell_Fire_ElementalDevastation",
            warning = true,
            lines = {"Blasts an enemy with Light, causing 2697 to 3122 Holy damage (full amount if the target is feared, stunned, or incapacitated)."}
        }, {
            name = "Prayer of Fortitude",
            icon = "Interface\\Icons\\Spell_Holy_PrayerOfFortitude",
            roles = {"dispel"},
            lines = {"Increases nearby allies' Health by 30% for 25 seconds."}
        }, {
            name = "Prayer of Purity",
            icon = "Interface\\Icons\\Spell_Holy_DispelMagic",
            lines = {"Removes 2 harmful Magic, Curse, or Disease effects from nearby allies, healing them for 5% of their maximum health per effect dispelled."}
        }, {
            name = "Prayer of Shield",
            icon = "Interface\\Icons\\Spell_Holy_PowerWordShield",
            roles = {"dispel"},
            lines = {"Shields nearby allies, absorbing 6835 to 7805 damage. Lasts 15 seconds. Spellcasting is not interrupted while the shield holds."}
        }}
    },

    scarlet_protector = {
        name = "Scarlet Protector",
        icon = "Interface\\Icons\\Spell_Holy_LayOnHands",
        flags = {"caster"},
        -- CHANGED: from a real combat log (see Scarlet Monestary Trash CSV) -
        -- stats not present in that log, never tested.
        stats = {armor = "X", fire = "X", nature = "X", frost = "X", shadow = "X", arcane = "X"},
        abilities = {{
            name = "Fist of Justice",
            icon = "Interface\\Icons\\Spell_Holy_SealOfMight",
            warning = true,
            lines = {"Stuns nearby enemies for 10 seconds."}
        }, {
            name = "Greater Light",
            icon = "Interface\\Icons\\Spell_Holy_LayOnHands",
            roles = {"stun"},
            lines = {"Heals a paladin ally for an amount equal to that paladin's maximum health."}
        }, {
            -- CHANGED: heal amount resolved from Spell.xlsx spell ID 36071 (the linked heal effect), not from in-game testing.
            name = "Judgement of Light",
            icon = "Interface\\Icons\\Spell_Holy_HealingAura",
            lines = {"Melee attacks against the afflicted target heal the attacker for 875 to 1095."}
        }, {
            name = "Purify",
            icon = "Interface\\Icons\\Spell_Holy_Purify",
            lines = {"Purifies a friendly target, removing 5 disease effects and 5 poison effects."}
        }, {
            separator = true,
            passive = true,
            name = "Passives"
        }, {
            name = "Improved Blocking",
            icon = "Interface\\Icons\\Ability_Defend",
            lines = {"Increases the caster's chance to block by 55%."}
        }, {
            -- CHANGED: radius confirmed from Spell.xlsx (spell 36068) + SpellRadius.csv lookup - not in-game tested.
            name = "Protection Aura",
            icon = "Interface\\Icons\\INV_Gauntlets_06",
            lines = {"Reduces damage taken by nearby allies within 30 yards by 30% for 20 seconds."}
        }}
    },

    scarlet_gallant = {
        name = "Scarlet Gallant",
        icon = "Interface\\Icons\\Spell_Holy_HolySmite",
        flags = {"caster"},
        -- CHANGED: from a real combat log (see Scarlet Monestary Trash CSV) -
        -- stats not present in that log, never tested.
        stats = {armor = "X", fire = "X", nature = "X", frost = "X", shadow = "X", arcane = "X"},
        abilities = {{
            name = "Crusader Strike",
            icon = "Interface\\Icons\\Spell_Holy_HolySmite",
            warning = true,
            lines = {"Inflicts 400 to 550 damage to an enemy and increases the Holy damage it takes by 180 per stack (up to 5 stacks). Lasts 25 seconds."}
        }, {
            name = "Divine Shield",
            icon = "Interface\\Icons\\Spell_Holy_DivineIntervention",
            lines = {"Protects the caster from all attacks and spells for 30 seconds, but increases the time between its attacks by 100% during that time."}
        }, {
            name = "Fist of Justice",
            icon = "Interface\\Icons\\Spell_Holy_SealOfMight",
            warning = true,
            lines = {"Stuns nearby enemies for 10 seconds."}
        }, {
            name = "Repentance",
            icon = "Interface\\Icons\\Spell_Holy_PrayerOfHealing",
            warning = true,
            roles = {"dispel"},
            lines = {"Incapacitates the target for up to 12 seconds and increases its Mana regeneration. Only works against Humanoids."}
        }, {
            separator = true,
            passive = true,
            name = "Passives"
        }, {
            -- CHANGED: radius confirmed from Spell.xlsx (spell 36136) + SpellRadius.csv lookup - not in-game tested.
            name = "Sanctity Aura",
            icon = "Interface\\Icons\\Spell_Holy_MindVision",
            lines = {"Increases Holy damage done by nearby party members within 30 yards by 30%."}
        }, {
            -- CHANGED: matched spell ID 36133 (custom range), % from linked spell 20424.
            name = "Seal of Command",
            icon = "Interface\\Icons\\Ability_Warrior_InnerRage",
            lines = {"Attacks deal additional Holy damage equal to 50% of normal weapon damage."}
        }}
    },

    scarlet_diviner = {
        name = "Scarlet Diviner",
        icon = "Interface\\Icons\\Spell_Nature_AstralRecalGroup",
        flags = {"caster"},
        -- CHANGED: from a real combat log (see Scarlet Monestary Trash CSV) -
        -- stats not present in that log, never tested.
        stats = {armor = "X", fire = "X", nature = "X", frost = "X", shadow = "X", arcane = "X"},
        -- CHANGED: all 30 "Prophecy: ..." cards below have empty Description_enUS
        -- in Spell.xlsx, but real tooltip text lives in AuraDescription_enUS
        -- instead (that column was missed in the original pass) - percentages
        -- cross-checked against EffectBasePoints_n+1 on spell IDs 36175-36204,
        -- all match the AuraDescription text exactly. Only Doppelganger and
        -- Instability remain genuinely vague ("Mirrored Presence." / "Fate
        -- remains unknown.") even in AuraDescription_enUS - real effect still
        -- needs external research.
        -- Prophecy trigger lines: some quotes real (from user), the rest still
        -- need to be found/tested in-game.
        abilities = {{
            name = "Cast Prophecy",
            icon = "Interface\\Icons\\Spell_Nature_AstralRecalGroup",
            warning = true,
            lines = {"Whenever the Diviner speaks a dialogue line, a random Prophecy is applied - either on a nearby target for 3 minutes, or on the Diviner himself for 1 minute. Each spoken line maps to a specific Prophecy (see individual cards)."}
        }, {
            name = "Prophecy: Aetherbound",
            icon = "Interface\\Icons\\Spell_Nature_WispSplode",
            lines = {"Immune to Arcane damage.", "Trigger line: \"Arcane fails to reach you.\""}
        }, {
            name = "Prophecy: Agony",
            icon = "Interface\\Icons\\Spell_Shadow_CurseOfSargeras",
            lines = {"Takes 3% health damage per second.", "Trigger line: \"Agony is your constant guest.\""}
        }, {
            name = "Prophecy: Alacrity",
            icon = "Interface\\Icons\\Ability_Warrior_InnerRage",
            warning = true,
            lines = {"Attack speed increased by 200%, movement speed increased by 50%. Spells are instant."}
        }, {
            name = "Prophecy: At the Edge",
            icon = "Interface\\Icons\\Racial_Troll_Berserk",
            warning = true,
            lines = {"Damage done doubled when at low health.", "Trigger line: \"Only at the edge will you prevail.\""}
        }, {
            name = "Prophecy: Callousness",
            icon = "Interface\\Icons\\Spell_Holy_DevotionAura",
            lines = {"Damage taken reduced by 75%.", "Trigger line: unknown - to be found/tested."}
        }, {
            name = "Prophecy: Cinderborn",
            icon = "Interface\\Icons\\Spell_Fire_SealOfFire",
            lines = {"Immune to Fire damage."}
        }, {
            name = "Prophecy: Cripple",
            icon = "Interface\\Icons\\Spell_Shadow_Cripple",
            lines = {"Attack and casting speed reduced by 100%, movement speed reduced by 50%.", "Trigger line: \"Your steps come too late.\""}
        }, {
            name = "Prophecy: Doomed",
            icon = "Interface\\Icons\\Spell_Shadow_DeathScream",
            lines = {"Damage taken increased by 300%."}
        }, {
            name = "Prophecy: Doppelganger",
            icon = "Interface\\Icons\\Spell_Nature_MirrorImage",
            -- CHANGED: AuraDescription_enUS (spell 36175-36204 range) is literally
            -- just "Mirrored Presence." - no numbers, no further mechanic detail
            -- to extract from Spell.xlsx.
            lines = {"Mirrored Presence."}
        }, {
            name = "Prophecy: Double-Edged",
            icon = "Interface\\Icons\\Ability_CriticalStrike",
            warning = true,
            lines = {"Increases all damage caused by 100% and all damage taken by 30%.", "Trigger line: \"Power, paid in blood.\""}
        }, {
            name = "Prophecy: Execution",
            icon = "Interface\\Icons\\INV_Sword_48",
            warning = true,
            lines = {"Deals 5x damage to targets below 50% HP."}
        }, {
            name = "Prophecy: Exposure",
            icon = "Interface\\Icons\\Ability_Hunter_SniperShot",
            lines = {"Damage taken increased by 20%. Cannot turn invisible."}
        }, {
            name = "Prophecy: Gloom",
            icon = "Interface\\Icons\\Spell_Shadow_AntiShadow",
            lines = {"Immune to Shadow damage."}
        }, {
            name = "Prophecy: Hailbound",
            icon = "Interface\\Icons\\Spell_Frost_ChillingArmor",
            lines = {"Immune to Frost damage.", "Trigger line: \"Winter cannot freeze your soul.\""}
        }, {
            name = "Prophecy: Helpless",
            icon = "Interface\\Icons\\Spell_Nature_RemoveCurse",
            lines = {"Healing taken reduced by 100%."}
        }, {
            name = "Prophecy: Instability",
            icon = "Interface\\Icons\\Spell_Nature_AstralRecalGroup",
            warning = true,
            -- CHANGED: AuraDescription_enUS is literally just "Fate remains
            -- unknown." - no numbers, no further mechanic detail to extract
            -- from Spell.xlsx.
            lines = {"Fate remains unknown.", "Trigger line: \"Fate is unstable.\""}
        }, {
            name = "Prophecy: Ironbound",
            icon = "Interface\\Icons\\Spell_Frost_Frost",
            lines = {"Immune to Physical damage.", "Trigger line: \"No steel will taste your blood.\""}
        }, {
            name = "Prophecy: Momentum",
            icon = "Interface\\Icons\\Spell_Shadow_DeathPact",
            warning = true,
            lines = {"Next attack's damage increased by 500%."}
        }, {
            name = "Prophecy: Negation",
            icon = "Interface\\Icons\\Ability_BackStab",
            warning = true,
            lines = {"Your attacks and spells ignore Armor and Resistances."}
        }, {
            name = "Prophecy: Nullify",
            icon = "Interface\\Icons\\Ability_BackStab",
            lines = {"Armor and resistances reduced by 100%.", "Trigger line: \"Your skin is but a veil.\""}
        }, {
            name = "Prophecy: Sanctified",
            icon = "Interface\\Icons\\Spell_Holy_PrayerOfHealing02",
            lines = {"Immune to Holy damage."}
        }, {
            name = "Prophecy: Shared Fate",
            icon = "Interface\\Icons\\SpiritLink",
            lines = {"Shares damage taken with nearby allies."}
        }, {
            name = "Prophecy: Spellward",
            icon = "Interface\\Icons\\INV_Ore_Arcanite_01",
            lines = {"Immune to Spell damage.", "Trigger line: \"You walk between the rain.\""}
        }, {
            name = "Prophecy: Terrifying",
            icon = "Interface\\Icons\\Spell_Shadow_Possession",
            warning = true,
            lines = {"Causing nearby enemies to flee in terror.", "Trigger line: \"Terror paves your way.\""}
        }, {
            name = "Prophecy: Undying",
            icon = "Interface\\Icons\\Spell_Shadow_AnimateDead",
            warning = true,
            lines = {"Cannot die."}
        }, {
            name = "Prophecy: Unfettered",
            icon = "Interface\\Icons\\Ability_Rogue_Trip",
            lines = {"Free from any bonds.", "Trigger line: unknown - to be found/tested."}
        }, {
            name = "Prophecy: Untouchable",
            icon = "Interface\\Icons\\INV_Shield_04",
            warning = true,
            lines = {"Immune to all damage."}
        }, {
            name = "Prophecy: Verdant",
            icon = "Interface\\Icons\\Spell_Nature_SpiritArmor",
            lines = {"Immune to Nature damage.", "Trigger line: \"Nature cannot harm you.\""}
        }, {
            name = "Prophecy: Vitality",
            icon = "Interface\\Icons\\Spell_Nature_UndyingStrength",
            lines = {"Healing taken increased by 100%, regenerating 1% of health every 1 sec.", "Trigger line: unknown - to be found/tested."}
        }, {
            name = "Prophecy: Weakness",
            icon = "Interface\\Icons\\Spell_Shadow_CurseOfMannoroth",
            lines = {"Damage caused reduced by 75%."}
        }}
    },

}

------------------------------------------------------------
-- Boss registry - one entry per boss (icon/flags/stats/abilities/adds),
-- referenced by key from SM_BOSS_ORDER above. Defined once each; add a
-- new boss here and add its key to SM_BOSS_ORDER to place it.
------------------------------------------------------------
local SM_BOSSES = {
    loksey = {
        name = "Loksey",
        icon = "Interface\\AddOns\\DungeonJournal\\Icons\\Loksey",
        flags = {"tauntable"},
        abilities = {{
            name = "Aspect of the Monkey",
            icon = "Interface\\Icons\\ability_hunter_aspectofthemonkey",
            color = "ffa335ee",
            lines = {"Loksey has +25% dodge and melee critical strike chance. This effect is lost when Loksey is sleeping."}
        }, {
            name = "Bloodlust",
            icon = "Interface\\Icons\\spell_nature_bloodlust",
            roles = {"dispel"},
            color = "ffff7d0a",
            lines = {"Loksey gains +30% attack speed for 1 minute. Recast every 20s if removed."}
        }, {
            name = "Freezing Trap",
            icon = "Interface\\Icons\\spell_frost_chainsofice",
            warning = true,
            roles = {"rogue"},
            color = "ffff7d0a",
            lines = {"Loksey places a frost trap near/below a random player that freezes the first entity that approaches, preventing all action for 10 seconds. Trap will exist for 300 seconds until Disarmed. Triggers Deep Freeze to the target that gets frozen. His own dogs can trigger this trap."},
            abilities = {{
                name = "Deep Freeze",
                icon = "Interface\\Icons\\ability_mage_coldasice",
                warning = true,
                roles = {"healer"},
                color = "ffff7d0a",
                lines = {"The target becomes Frozen and being unable to take any actions and takes 20% health Frost damage per second for 10 seconds."}
            }}
        }, {
            name = "Tranquilizing Poison",
            icon = "Interface\\Icons\\spell_nature_slowpoison",
            roles = {"poison"},
            color = "ffff7d0a",
            lines = {"Loksey casts Tranquilizing Poison on a player who gains a Frenzy effect. It removes all Frenzy effects, reduces movement speed by 50% and drains 10 rage per second and prevents its generation.",
                     "After 5 seconds the player gets slept for 20 seconds."}
        }, {
            name = "Paralyzing Poison",
            icon = "Interface\\Icons\\ability_creature_poison_04",
            warning = true,
            roles = {"poison"},
            color = "ffff7d0a",
            lines = {"Loksey throws out a poison volley at all enemies. The poison inflicts 125 to 145 Nature damage per stack every 2 sec and lasts 20 seconds.",
                     "At 5 stacks it stuns the user for 10/11 seconds and removes all stacks."}
        }, {
            name = "Power Shot",
            icon = "Interface\\Icons\\inv_spear_07",
            warning = true,
            color = "ffff7d0a",
            -- CHANGED: description confirmed from Spell.xlsx (spell 35841, via
            -- "SM 6 bosses.csv"); the damage value (spell 35844 "Power Shot
            -- DMG") is 0 in the sheet, so the number still needs testing.
            lines = {"Loksey fires a powerful shot that pierces through all enemies in its path, ignoring armor. Damage not yet known."}
        }, {
            name = "Scare Beast",
            icon = "Interface\\Icons\\ability_druid_cower",
            color = "ffff7d0a",
            lines = {"Loksey casts this whenever there is a 'beast' in the raid, fearing it for 8 seconds.",
                     "This can also fear his own dogs."}
        }, {
            name = "Summon Beast",
            icon = "Interface\\Icons\\ability_mount_whitedirewolf",
            color = "ffff7d0a",
            lines = {"Loksey summons a Scarlet Tracking Hound every 40? seconds to aid him in battle. This dog will not respawn if killed unlike his other dogs."}
        }},
        adds = {{
            name = "Scarlet Tracking Hound",
            icon = "Interface\\Icons\\temp",
            roles = {},
            color = "ffcc0000",
            lines = {"Four of these accompany Loksey into battle.",
                     "They respawn if killed."},
            abilities = {{
                name = "Infected Wound",
                icon = "Interface\\Icons\\spell_nature_nullifydisease",
                roles = {"dispel"},
                color = "ff00ccff",
                lines = {"Hounds apply a stacking debuff which increases physical damage taken by 3 per stack up to 99 stacks."}
            }}
        }}
    },

    brigitte = {
        name = "Brigitte Abbendis",
        icon = "Interface\\AddOns\\DungeonJournal\\Icons\\BrigitteAbbendis",
        flags = {"tauntable"},
        -- NOTE: values from Spell.dbc (IDs 35848-35877), every damage/percent
        -- below re-confirmed against the "SM 6 bosses.csv" combat log +
        -- Spell.xlsx. Phase 2 is the mounted phase - she summons the Scarlet
        -- Charger and swaps to its abilities.
        abilities = {{
            separator = true,
            name = "Phase 1"
        }, {
            name = "Command Gesture",
            icon = "Interface\\Icons\\Ability_Hunter_KillCommand",
            lines = {"Used at the pull while she is still at range. No damage or debuff recorded in logs - it appears to be the flavour cast before she closes to melee."}
        }, {
            name = "Righteous Charge",
            icon = "Interface\\Icons\\Ability_Warrior_VictoryRush",
            warning = true,
            roles = {"tank"},
            lines = {"Charges an enemy, inflicting normal damage plus 500, gaining aggro and stunning them."}
        }, {
            name = "Shield Bash",
            icon = "Interface\\Icons\\INV_Shield_05",
            warning = true,
            lines = {"Slam the target with your shield, causing 1794 to 2170 damage, and dispels 1 magic effect on the target."}
        }, {
            name = "Consecration",
            icon = "Interface\\Icons\\Spell_Holy_InnerFire",
            warning = true,
            lines = {"Consecrates the ground on the closest and furthest target, dealing Holy damage every second to anyone standing in the area. Won't be cast if mana is empty."}
        }, {
            name = "Provocation",
            icon = "Interface\\Icons\\Ability_Warrior_InnerRage",
            lines = {"Taunts and forces all nearby enemies within 10 yards to focus attacks on her for 8 seconds."}
        }, {
            separator = true,
            name = "Phase 2"
        }, {
            name = "Fist of Justice",
            icon = "Interface\\Icons\\Spell_Holy_SealOfMight",
            warning = true,
            lines = {"Casts at 20% health left. Stuns nearby enemies for up to 10 seconds."}
        }, {
            name = "Lay on Hands",
            icon = "Interface\\Icons\\Spell_Holy_LayOnHands",
            warning = true,
            lines = {"Casts at 20% health left. Heals to full health."}
        }, {
            name = "Scarlet Charger",
            icon = "Interface\\Icons\\mount_scarlet_charger",
            lines = {"Casts at 20% health left. She summons her mount, increasing her speed by 100%."}
        }, {
            name = "Stormbolt",
            icon = "Interface\\Icons\\Ability_ThunderClap",
            roles = {"healer", "tank", "reflect"},
            lines = {"Hurls a hammer that strikes an enemy for 1897 to 2327 Holy damage every 1.5 seconds. Reflectable"}
        }, {
            name = "Hoof Kick",
            icon = "Interface\\Icons\\INV_Misc_MonsterScales_05",
            warning = true,
            lines = {"Inflicts 1500 to 2050 damage on enemies in a cone behind the caster, knocking them back."}
        }, {
            name = "Trampling Charge",
            icon = "Interface\\Icons\\INV_Misc_MonsterScales_05",
            warning = true,
            lines = {"Inflicts 1800 to 2298 damage to enemies in a cone in front of the caster, knocking them back."}
        }, {
            name = "Crash",
            icon = "Interface\\Icons\\Ability_WarStomp",
            warning = true,
            lines = {"Inflicts 400% weapon damage to an already wounded enemy and stuns them."}
        }, {
            name = "Consecration (phase 2)",
            icon = "Interface\\Icons\\Spell_Holy_InnerFire",
            lines = {"Consecrates the ground on the closest and furthest target, dealing 1150 to 1520 Holy damage instantly and 10% health damage per 0.95s to anyone standing in the area. Lasts 8 seconds. Won't be cast if mana is empty."}
        }, {
            name = "Close Quarters Combat Experience",
            icon = "Interface\\Icons\\Ability_Warrior_OffensiveStance",
            warning = true,
            roles = {"tank"},
            lines = {"Increases her attack speed by 100% and the Physical damage she deals by 100% for 10 seconds."}
        }, {
            separator = true,
            passive = true,
            name = "Passives"
        }, {
            -- CHANGED: spell 36172, logged frequently in "SM 6 bosses.csv" -
            -- the same always-on trait as the Scarlet trash. No Spell.xlsx
            -- text; 55% is the value used on the trash entries.
            name = "Improved Blocking",
            icon = "Interface\\Icons\\Ability_Defend",
            lines = {"Increases her chance to block by 55%."}
        }},
        adds = {{
            name = "Scarlet Sharpshooter",
            icon = "Interface\\Icons\\temp",
            color = "ffcc0000",
            lines = {"Four of these accompany Brigitte Abbendis into battle."},
            abilities = {{
                name = "Longshot",
                icon = "Interface\\Icons\\inv_spear_07",
                color = "ff00ccff",
                lines = {"Shoots an enemy, inflicting an additional 100 ranged damage and slowing its movement speed by 60% for 3 seconds."}
            }, {
                name = "Explosive Shot",
                icon = "Interface\\Icons\\inv_musket_03",
                color = "ff00ccff",
                lines = {"Inflicts 1550 to 2100 Fire damage and knocks the target back, silencing it for 6 seconds and slowing its movement speed by 50% for 6 seconds."}
            }, {
                name = "Volley",
                icon = "Interface\\Icons\\ability_marksmanship",
                color = "ff00ccff",
                lines = {"Continuously fires a volley of ammo at the target area, inflicting 500 to 550 Arcane damage every second to enemies within 8 yards for 12 seconds."}
            }}
        }}
    },

    vishas = {
        name = "Vishas",
        icon = "Interface\\AddOns\\DungeonJournal\\Icons\\Vishas",
        flags = {"tauntable"},
        -- NOTE: values below come from Spell.dbc (IDs 35880-35900). Percentages
        -- are the real $s values (DBC stores them as value-1) and tick rates are
        -- EffectAmplitude in milliseconds. Damage ranges seen in combat logs are
        -- noted where they add context.
        abilities = {{
            name = "Sear",
            icon = "Interface\\Icons\\Spell_Fire_FlameShock",
            roles = {"tank"},
            lines = {"Vishas' main attack on his current target - a Flame Lash for 550 to 650 Fire damage."}
        }, {
            name = "Shadow Word: Pain",
            icon = "Interface\\Icons\\Spell_Shadow_ShadowWordPain",
            warning = true,
            roles = {"dispel"},
            lines = {"A raid-wide curse dealing 5% of a player's health every 3 seconds. Applied every 5-10 seconds."}
        }, {
            name = "Impending Sentence",
            icon = "Interface\\Icons\\Spell_Holy_RetributionAura",
            warning = true,
            lines = {"Every 15-20 seconds Vishas sentences a player and after 3 seconds Shared Sentence is applied to that player. Applied every 20 seconds."},
            abilities = {{
                name = "Shared Sentence",
                icon = "Interface\\Icons\\Spell_Holy_RighteousFury",
                warning = true,
                roles = {"healer"},
                lines = {"Deals ~2000 to 8000 damage. Pass it by touching another player. Reflectable.",
                         "If passed EARLY (High time): HIGH damage to YOU / LOW damage to ALLY.",
                         "If passed LATE (Low time): LOW damage to YOU / HIGH damage to ALLY.",
                         "If NOT passed (0s left): YOU take MAX damage (8000)."},
                abilities = {{
                    name = "Recidivism",
                    icon = "Interface\\Icons\\Spell_Holy_FistOfJustice",
                    lines = {"Increase damage taken from Shared Sentence by 50%. Acquired by being dealt damage by Shared Sentence. Stacks up to 10. Lasts for 30 seconds."}
                }}
            }}
        }, {
            name = "Atonement",
            icon = "Interface\\Icons\\INV_Belt_18",
            warning = true,
            roles = {"healer"},
            lines = {"Teleports a raid member to one of three 'sacrifice' benches and stuns them, dealing 20% of their health every 2 seconds for 12 seconds. Applied every 20 seconds."}
        }, {
            name = "Ordeal Grip",
            icon = "Interface\\Icons\\INV_Gauntlets_04",
            roles = {"dispel"},
            lines = {"Slows movement by 60% and increases all damage taken by 50%. Lasts 8 seconds.",
                     "Can be reflected back onto Vishas? Applied every 12-15 seconds."}
        }, {
            name = "Pummel",
            icon = "Interface\\Icons\\INV_Gauntlets_04",
            lines = {"Pummel the target for 1150 to 1450 damage. It also interrupts spellcasting and prevents any spell in that school from being cast for 5 seconds."}
        }}
    },

    herod = {
        name = "Herod",
        icon = "Interface\\AddOns\\DungeonJournal\\Icons\\Herod",
        flags = {"notalwaystauntable"},
        abilities = {{
            name = "Rushing Charge",
            icon = "Interface\\Icons\\ability_warstomp",
            lines = {"At the start of the fight and after each Bladestorm, Herod charges towards the highest threat target.",
                     "Increasing his movement speed by 50% for 4 sec. and causes it to inflict an additional 1? damage on its first attack."}
        }, {
            name = "Deep Wound",
            icon = "Interface\\Icons\\ability_backstab",
            lines = {"Bleeding for 10% health damage every 3 sec. Healing effects reduced by 10%. Lasts for 21 seconds. Stacks up to 5 times."}
        }, {
            name = "Cleaving Blow",
            icon = "Interface\\Icons\\ability_warrior_cleave",
            roles = {"melee"},
            lines = {"Herod sometimes cleaves in a 90 degree frontal arc."}
        }, {
            name = "Wound",
            icon = "Interface\\Icons\\ability_backstab",
            lines = {"Bleeding for 550 damage every 3 sec. Lasts 21 seconds."}
        }, {
            name = "Echo Clap",
            icon = "Interface\\Icons\\spell_nature_thunderclap",
            warning = true,
            lines = {"Herod interrupts all cast casting within 30? yards every ~10 seconds and prevent spells cast from that school for 5 seconds. Also dealing 300 to 500 damage."}
        }, {
            name = "Death Wish",
            icon = "Interface\\Icons\\spell_shadow_deathpact",
            lines = {"After 3 minutes Herod cast Death Wish Increasing his attack speed by 50% and crit chance by 15% for 3 min, but also taking 15% more damage."}
        }, {
            name = "Bladestorm",
            icon = "Interface\\Icons\\ability_whirlwind",
            warning = true,
            lines = {"Attacks nearby enemies in a whirlwind of steel that lasts 10 sec., inflicting 50%? weapon damage every 0.5 sec. Herod is immune during this time."}
        }, {
            name = "Blades of Light",
            icon = "Interface\\Icons\\ability_whirlwind",
            lines = {"Every 10-15 seconds Herod yells 'Blades of Light' and after 2 seconds deals 125% weapon damage (and a bleed?) to all enemies within 8 yards."}
        }, {
            name = "Enrage",
            icon = "Interface\\Icons\\spell_shadow_unholyfrenzy",
            lines = {"Frenzy effect. Melee damage increased by 5%. Stacks to 20."}
        }, {
            name = "Demoralized",
            icon = "Interface\\Icons\\spell_shadow_deathscream",
            warning = true,
            lines = {"Reduces damage and healing done by 10% for 1 minute. Triggers Cowardice at 5 stacks.",
                     "Stacks are removable by doing 4000? damage within 5? seconds."},
            abilities = {{
                name = "Cowardice",
                icon = "Interface\\Icons\\ability_cheapshot",
                lines = {"Feared for 8 seconds and gains aggro of the boss during that time. Boss also becomes untauntable?"}
            }}
        }},
        -- CHANGED: from testing - confirmed real add of Herod, not a
        -- standalone trash pull.
        adds = {{
            name = "Scarlet Trainee",
            icon = "Interface\\Icons\\INV_Sword_04",
            lines = {"Herod summons 20 Scarlet Trainees upon his death, at the top of the stairs."}
        }}
    },

    brother_michael = {
        name = "Brother Michael",
        icon = "Interface\\AddOns\\DungeonJournal\\Icons\\BrotherMichael",
        flags = {"tauntable"},
        -- NOTE: values from Spell.dbc (IDs 35940-35951), cross-checked against
        -- the "SM 6 bosses.csv" combat log. Percentages are the real $s values
        -- (DBC stores them as value-1).
        abilities = {{
            name = "Curse of Thorns",
            icon = "Interface\\Icons\\Spell_Shadow_AntiShadow",
            warning = true,
            roles = {"dps", "decurse"},
            lines = {"The target takes twice the damage they deal. Lasts 45 seconds."}
        }, {
            name = "Thorned Roots",
            icon = "Interface\\Icons\\Spell_Nature_StrangleVines",
            warning = true,
            roles = {"healer"},
            lines = {"Roots a player and deals 20% of their maximum health as Nature damage every second for 8 seconds.",
                     "When the roots collapse, thorns explode outward to all targets in Line of Sight dealing 5380 to 6180 damage and stunning for 2 seconds."}
        }, {
            name = "Fists of Fire",
            icon = "Interface\\Icons\\Spell_Fire_Immolation",
            roles = {"tank"},
            lines = {"90% of Brother Michael's Physical damage becomes Fire damage for 25 seconds."}
        }, {
            name = "Four Finger Death Punch",
            icon = "Interface\\Icons\\Spell_Shadow_CorpseExplode",
            warning = true,
            roles = {"tank"},
            lines = {"Every 10 seconds the tank takes receives a stack of Four Finger Death Punch.",
                     "Whenever the tank reaches 4 stacks he will explode taking 50000 to 100000 damage."}
        }, {
            name = "Soulbind",
            icon = "Interface\\Icons\\Spell_Shadow_Haunting",
            warning = true,
            lines = {"Brother Michael casts Soulbind on everyone (including himself) in his line of sight and binds them together for 8 seconds.",
                     "20% of the damage taken is split among the bound."}
        }, {
            name = "Grip Break",
            icon = "Interface\\Icons\\Ability_Warrior_Disarm",
            lines = {"Disarms the target for 6 seconds."}
        }, {
            name = "Kick",
            icon = "Interface\\Icons\\Ability_kick",
            warning = true,
            lines = {"Kicks a player back 50 yards and sends them to the death realm, causing Disembodied."},
            abilities = {{
                name = "Disembodied",
                icon = "Interface\\Icons\\ability_vanish",
                lines = {"The target becomes a ghost and can see mobs that are in the death realm. If caught by the mobs they will die."}
            }}
        }, {
            separator = true,
            passive = true,
            name = "Passives"
        }, {
            -- CHANGED: spell 36155, logged in "SM 6 bosses.csv" - self-buff he
            -- keeps up. Spell.xlsx: "$s1" = -21+1 = -20, "$s2" = 19+1 = 20;
            -- DurationIndex 3 = 60s. (Same effect as the Scarlet Monk's.)
            name = "Inner Fire",
            icon = "Interface\\Icons\\Spell_Holy_InnerFire",
            lines = {"Increases the damage he deals by 20% and reduces damage he takes by 20%. Refreshed roughly every 60 seconds."}
        }}
    },

    doan = {
        name = "Doan",
        icon = "Interface\\AddOns\\DungeonJournal\\Icons\\Doan",
        flags = {"tauntable"},
        -- NOTE: values from Spell.dbc (IDs 35954-35989), cross-checked against
        -- the "SM 6 bosses.csv" combat log. Doan rotates between three
        -- elemental stances (Arcane, Frost, Fire), each with its own set of
        -- abilities - including an Elemental Ward that reflects that school's
        -- spells. Shared abilities are listed under "All Phases".
        abilities = {{
            separator = true,
            name = "All Phases"
        }, {
            name = "Brilliance Aura",
            icon = "Interface\\Icons\\Spell_Nature_Brilliance",
            lines = {"Regenerates 550 mana every 5 seconds."}
        }, {
            name = "Arcane Pulse",
            icon = "Interface\\Icons\\Spell_Arcane_ArcaneResilience",
            warning = true,
            lines = {"Magically pulses for 100 Arcane damage and interrupts spellcasting, locking that school for a few seconds."}
        }, {
            name = "Blink",
            icon = "Interface\\Icons\\Spell_Arcane_Blink",
            lines = {"After phase swap, Doan teleports a short distance."}
        }, {
            name = "Evocation",
            icon = "Interface\\Icons\\Spell_Nature_Purge",
            warning = true,
            roles = {"kick"},
            lines = {"Channels to regenerate 5% of his total mana per second. Lasts 10 seconds."}
        }, {
            -- CHANGED: spell 35955, logged in "SM 6 bosses.csv". Spell.xlsx
            -- absorb value is the 999,999,999 "unlimited" sentinel - it is
            -- mana-bound, same as the Scarlet Sorcerer's.
            name = "Mana Shield",
            icon = "Interface\\Icons\\Spell_Shadow_DetectLesserInvisibility",
            lines = {"Absorbs incoming damage by draining his own mana instead."}
        }, {
            separator = true,
            name = "Arcane Phase"
        }, {
            name = "Arcanebolt",
            icon = "Interface\\Icons\\Spell_Nature_StarFall",
            lines = {"Blasts an enemy for 1040 to 1390 Arcane damage every 0.5 seconds while channeling."}
        }, {
            name = "Greater Polymorph",
            icon = "Interface\\Icons\\Spell_Nature_Brilliance",
            roles = {"dispel"},
            lines = {"Transforms an enemy into a sheep for 60 seconds."}
        }, {
            name = "Slow",
            icon = "Interface\\Icons\\Spell_Nature_Slow",
            roles = {"dispel"},
            lines = {"Reduces the target's movement speed by 50% and attack speed by 50% for 20 seconds."}
        }, {
            name = "Siphon Magic",
            icon = "Interface\\Icons\\Spell_Nature_Purge",
            lines = {"Purges all harmful magic effects from himself, restoring mana for each effect removed."}
        }, {
            -- CHANGED: spell 35959, logged in "SM 6 bosses.csv". Spell.xlsx:
            -- "Reflects Arcane spells back at their caster"; DurationIndex 3 = 60s.
            name = "Arcane Ward",
            icon = "Interface\\Icons\\Spell_Arcane_PrismaticCloak",
            warning = true,
            roles = {"caster"},
            lines = {"Reflects Arcane spells cast at him back at the caster for 60 seconds - stop casting Arcane while it is up."}
        }, {
            separator = true,
            name = "Frost Phase"
        }, {
            name = "Icebolt",
            icon = "Interface\\Icons\\Spell_Frost_FrostBolt02",
            roles = {"healer"},
            lines = {"Launches a bolt of frost for 4200 to 5110 Frost damage and reduces the next healing effect on the target by 90%."}
        }, {
            name = "Ice Blast",
            icon = "Interface\\Icons\\Spell_Frost_Glacier",
            warning = true,
            roles = {"healer"},
            lines = {"Deals 15% of the target's health every second for 10 seconds."}
        }, {
            -- CHANGED: spell 35958, logged in "SM 6 bosses.csv". Spell.xlsx:
            -- "Reflects Frost spells back at their caster"; DurationIndex 3 = 60s.
            name = "Frost Ward",
            icon = "Interface\\Icons\\Spell_Frost_FrostWard",
            warning = true,
            roles = {"caster"},
            lines = {"Reflects Frost spells cast at him back at the caster for 60 seconds - stop casting Frost while it is up."}
        }, {
            name = "Numbing Cold",
            icon = "Interface\\Icons\\Spell_Frost_FrostArmor",
            warning = true,
            lines = {"The ground gets icy. After 3 seconds your attack and movement speed gets reduced by 30%.",
                     "After 6? seconds your attack, movement and casting speed reduced by 40%.",
                     "After 10 seconds of standing applies Chilled to the Bone."},
            abilities = {{
                name = "Chilled to the Bone",
                icon = "Interface\\Icons\\spell_frost_frostnova",
                lines = {"Your unable to move and your attack and casting speed is reduced by 50% and after 5 seconds become Frozen Solid."},
                abilities = {{
                    name = "Frozen Solid",
                    icon = "Interface\\Icons\\spell_frost_frost",
                    lines = {"Your frozen in place for 10 seconds and get X Frost Damage every X seconds."}
                }}
            }}
        }, {
            separator = true,
            name = "Fire Phase"
        }, {
            name = "Flamebolt",
            icon = "Interface\\Icons\\Spell_Fire_FlameBolt",
            lines = {"Hurls a fiery ball for 5750 to 6800 Fire damage plus 250 Fire damage every 0.5 sec. for 8 seconds."}
        }, {
            -- CHANGED: spell 35957, logged in "SM 6 bosses.csv". Spell.xlsx:
            -- "Reflects Fire spells back at their caster"; DurationIndex 3 = 60s.
            name = "Fire Ward",
            icon = "Interface\\Icons\\Spell_Fire_FireArmor",
            warning = true,
            roles = {"caster"},
            lines = {"Reflects Fire spells cast at him back at the caster for 60 seconds - stop casting Fire while it is up."}
        }, {
            name = "Flamestrike",
            icon = "Interface\\Icons\\Spell_Fire_SelfDestruct",
            lines = {"Calls down a pillar of fire for 1555 to 1840 Fire damage on a random target, then 575 Fire damage every second to anyone standing in it for 8 seconds."}
        }, {
            name = "Dragon Breath",
            icon = "Interface\\Icons\\Spell_Fire_Fire",
            warning = true,
            roles = {"tank"},
            lines = {"Inflicts 1850 to 2230 Fire damage in a cone in front of Doan. This will set any bookshelves ablaze which he hits."},
            abilities = {{
                name = "Searing Heat",
                icon = "Interface\\Icons\\Spell_Fire_Incinerate",
                lines = {"Continually inflicts Fire damage on the raid."}
            }}
        }}
    },

    renault_mograine = {
        name = "Renault Mograine",
        icon = "Interface\\AddOns\\DungeonJournal\\Icons\\Mograine",
        flags = {"notalwaystauntable"},
        -- NOTE: values from Spell.dbc (IDs 33456-36021), cross-checked against
        -- the "SM mograine fairbanks.csv" combat log + Spell.xlsx. Percentages
        -- are the real $s values (DBC stores them as value-1).
        abilities = {{
            separator = true,
            name = "Renault Mograine"
        }, {
            name = "Eye for an Eye",
            icon = "Interface\\Icons\\Spell_Holy_EyeforanEye",
            warning = true,
            lines = {"All of the damage dealt to him is reflected back at the raid, divided between each member."}
        }, {
            name = "Crusader Strike",
            icon = "Interface\\Icons\\Spell_Holy_CrusaderStrike2",
            roles = {"tank", "dispel"},
            lines = {"Inflicts 800 to 1100 damage to an enemy and increases the Holy damage it takes by 20% per Crusader Strike. Can be applied up to 5 times. Lasts 25 seconds."}
        }, {
            name = "Pillar of Light",
            icon = "Interface\\Icons\\Spell_Holy_ReviveChampion",
            lines = {"Mograine summons a Pillar of Light every ~15-20 seconds, which disorientates anyone who looks at it for 6 seconds while it's being cast. It deals 500 Holy damage to anyone in its' line of sight every second."}
        }, {
            -- CHANGED: spell 36003, logged in "SM mograine fairbanks.csv".
            -- Spell.xlsx: blind, DurationIndex 32 = 6s.
            name = "Blinding Light",
            icon = "Interface\\Icons\\Spell_Holy_MindVision",
            warning = true,
            lines = {"Emits a flash of light that blinds nearby enemies facing him for 6 seconds."}
        }, {
            name = "Purify",
            icon = "Interface\\Icons\\spell_holy_purify",
            lines = {"Mograine purifies a friendly target, removing 1 disease effect and 1 poison effect."}
        }, {
            -- CHANGED: spell 1020, logged in "SM mograine fairbanks.csv".
            -- DurationIndex 1 = 10s.
            name = "Divine Shield",
            icon = "Interface\\Icons\\Spell_Holy_DivineIntervention",
            warning = true,
            lines = {"Becomes immune to all attacks and spells for 10 seconds, but cannot take offensive actions during it."}
        }, {
            -- CHANGED: spell 9257, logged in "SM mograine fairbanks.csv".
            name = "Lay on Hands",
            icon = "Interface\\Icons\\Spell_Holy_LayOnHands",
            warning = true,
            lines = {"Heals himself to full health, draining all of his remaining mana."}
        }, {
            name = "Aura",
            icon = "Interface\\Icons\\spell_holy_auramastery",
            lines = {"Mograine swaps between 5 auras at random every 20 seconds."},
            abilities = {{
                name = "Retribution Aura",
                icon = "Interface\\Icons\\spell_holy_auraoflight",
                lines = {"Does 125 Holy damage to anyone who hits Mograine and doubles the damage of Eye for an Eye."}
            }, {
                name = "Devotion Aura",
                icon = "Interface\\Icons\\spell_holy_devotionaura",
                lines = {"Increases his armor by 2100."}
            }, {
                name = "Fire Resistance Aura",
                icon = "Interface\\Icons\\spell_fire_sealoffire",
                lines = {"Increases his Fire resistance by 180."}
            }, {
                name = "Frost Resistance Aura",
                icon = "Interface\\Icons\\spell_frost_wizardmark",
                lines = {"Increases his Frost resistance by 180."}
            }, {
                name = "Shadow Resistance Aura",
                icon = "Interface\\Icons\\spell_shadow_sealofkings",
                lines = {"Increases his Shadow resistance by 180."}
            }}
        }, {
            separator = true,
            name = "Sally Whitemane"
        }, {
            name = "Scarlet Resurrection",
            icon = "Interface\\Icons\\spell_holy_resurrection",
            warning = true,
            lines = {"When Mograine dies, Whitemane resurrects him and the fight continues."}
        }, {
            name = "Holy Smite",
            icon = "Interface\\Icons\\Spell_Holy_HolySmite",
            roles = {"kick"},
            lines = {"Whitemane's main cast, smiting a target for 2730 to 3030 Holy damage."}
        }, {
            name = "Holy Fire",
            icon = "Interface\\Icons\\Spell_Holy_SearingLight",
            warning = true,
            roles = {"kick"},
            lines = {"Inflicts 1275 to 1650 Holy damage plus 830 Holy damage every 3 seconds, and dispels a positive effect from the target on each periodic damage tick."}
        }, {
            name = "Absolution",
            icon = "Interface\\Icons\\Spell_Holy_RighteousFury",
            warning = true,
            roles = {"tank"},
            lines = {"Smites an enemy, inflicting 4000 to 5000 Holy damage."}
        }, {
            name = "Eradication",
            icon = "Interface\\Icons\\spell_holy_righteousfury",
            warning = true,
            roles = {"tank"},
            lines = {"Smites an enemy, inflicting 10000 to 12000 Holy damage."}
        }, {
            name = "Heal",
            icon = "Interface\\Icons\\Spell_Holy_Heal",
            warning = true,
            roles = {"kick"},
            lines = {"Whitemane heals herself (or Mograine) for 90000 to 100000."}
        }, {
            name = "Dispel Magic",
            icon = "Interface\\Icons\\Spell_Holy_DispelMagic",
            lines = {"Whitemane dispels 2 magic spells from herself."}
        }, {
            name = "Power Word: Shield",
            icon = "Interface\\Icons\\Spell_Holy_PowerWordShield",
            roles = {"dispel"},
            lines = {"Shields herself, absorbing 15000 damage."}
        }, {
            name = "Dominate Mind",
            icon = "Interface\\Icons\\spell_shadow_shadowworddominate",
            warning = true,
            roles = {"cc"},
            -- CHANGED: spell 36013, from "SM mograine fairbanks.csv".
            -- DurationIndex 8 = 15s.
            lines = {"Mind controls a player for 15 seconds."}
        }, {
            -- CHANGED: spell 9256, logged in "SM mograine fairbanks.csv".
            -- Spell.xlsx: sleep, DurationIndex 2 = 30s, broken by damage.
            name = "Deep Sleep",
            icon = "Interface\\Icons\\Spell_Nature_Sleep",
            warning = true,
            lines = {"Puts nearby enemies to sleep for up to 30 seconds. Any damage wakes them."}
        }}
    },

    fairbanks = {
        name = "Fairbanks",
        icon = "Interface\\AddOns\\DungeonJournal\\Icons\\Fairbanks",
        flags = {"tauntable"},
        -- NOTE: values from Spell.dbc (IDs 36024-36213), Bile Vomit /
        -- Power Word: Barrier / Claustrophobia re-confirmed against the
        -- "SM mograine fairbanks.csv" combat log + Spell.xlsx (that log only
        -- caught the pull, so the rest are still Spell.dbc-only).
        abilities = {{
            name = "Bile Vomit",
            icon = "Interface\\Icons\\Spell_Shadow_PlagueCloud",
            roles = {"tank"},
            lines = {"Shoots a cloud of bile in a cone in front of him, reducing armor by 650 and inflicting 1280 to 1620 Nature damage and 330 Nature damage every 5 seconds for 30 seconds. Stacks up to 10 times."}
        }, {
            -- CHANGED: spell 36027 - Spell.xlsx aura text is "Stomp damage and
            -- radius increased"; user confirms it also visibly enlarges
            -- players. DurationIndex 18 = 20s.
            name = "Claustrophobia",
            icon = "Interface\\Icons\\Spell_Shadow_Shadesofdarkness",
            warning = true,
            lines = {"The walls press inward for 20 seconds - all players grow in size and the damage and radius of his Stomp are increased."}
        }, {
            name = "Blasphemous Vitality",
            icon = "Interface\\Icons\\spell_shadow_unholystrength",
            lines = {"Regenerates 1% of total Health every 5 seconds."}
        }, {
            name = "Power Word: Barrier",
            icon = "Interface\\Icons\\spell_holy_powerwordshield",
            lines = {"Shields himself, absorbing 9260 to 9460 damage for 15 seconds."}
        }, {
            name = "All-Consuming Hatred",
            icon = "Interface\\Icons\\spell_shadow_sacrificialshield",
            lines = {"Damage done increased by 50%. Immune to Taunt effects. Not sure when he does this."}
        }, {
            name = "Stomp",
            icon = "Interface\\Icons\\ability_kick",
            lines = {"Whenever players are too close to each other triggers Stomp, interrupting spellcasting and prevents any spell in that school from being cast for 0.5 seconds."}
        }, {
            name = "Panic",
            icon = "Interface\\Icons\\spell_shadow_auraofdarkness",
            lines = {"Weakens your spirit, causing Panic to accumulate over time. Upon reaching 10 stacks, triggers Fear."},
            abilities = {{
                name = "Fear",
                icon = "Interface\\Icons\\spell_shadow_possession",
                roles = {"dispel"},
                lines = {"Become feared for 8 seconds."}
            }}
        }}
    },
}

------------------------------------------------------------
-- Builder: expand the order list + registry above into the flat table
-- shape the Bosses view expects (see AGENTS.md "Data model"). Nothing
-- below this point encodes raid content - only edit it if the addon's
-- expected data shape changes.
------------------------------------------------------------

local function BuildSMBosses()
    local bosses = {}
    for _, key in ipairs(SM_BOSS_ORDER) do
        local boss = { key = key }
        for field, value in pairs(SM_BOSSES[key]) do
            boss[field] = value
        end
        table.insert(bosses, boss)
    end
    return bosses
end

local function BuildSMTrash()
    local trash = {}
    for _, entry in ipairs(SM_TRASH_ORDER) do
        if type(entry) == "table" and entry.separator then
            table.insert(trash, entry)
        else
            local key, count
            if type(entry) == "table" then
                key, count = entry.key, entry.count
            else
                key = entry
            end
            local mob = SM_TRASH_MOBS[key]
            local pack = { key = key, count = count }
            for field, value in pairs(mob) do
                pack[field] = value
            end
            table.insert(trash, pack)
        end
    end
    return trash
end

table.insert(DungeonJournal_Raids, {
    key = "SM",
    name = "Scarlet Monastery",
    expanded = false,
    trashExpanded = false,
    trash = BuildSMTrash(),
    bosses = BuildSMBosses(),
})
